version: '3'
services:
  trader:
    build: ./
    env_file: .env
  kafka:
    image: ches/kafka
    environment:
      - ZOOKEEPER_IP=zookeeper
    depends_on:
      - zookeeper
  zookeeper:
    image: zookeeper:3.4
